spring:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: us-east-1
s3:
  bucket:
    name: ${BUCKET_NAME}
    prefix: ${PREFIX}